version: '3'

services:
  wordpress:
    image: felipeelia/wordpress:latest
#    image: felipeelia/wordpress:php-5.6
    environment:
    - WP_DB_NAME=feliz7class
    - WP_DB_USER=root
    - WP_DB_PASSWORD=wordpress
    - WP_DB_HOST=mysql
    links:
      - mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../app:/var/www/html
      - ./htaccess_dev:/var/www/html/.htaccess
      - ./dev.ini:/usr/local/etc/php/conf.d/dev.ini
#    environment:
#      - XDEBUG=true

  mysql:
    image: mariadb
    volumes:
      - ../db_data:/var/lib/mysql
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_HOST: '%'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=wordpress
      - UPLOAD_LIMIT=3000M
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions

#  node:
#    image: node
#    user: node
#    working_dir: /app
#    volumes:
#      - ../dev/wp-content/themes/THEME_NAME:/app
#    ports:
#      - 35729:35729
#    command: bash -c 'npm install && /app/node_modules/grunt/bin/grunt'
